In [ ]:
from src.donnees import import_donnees, renomer_cle_jointure, concatenation_annees
from src.nettoyage import recodage, mapping_renommer_colonnes, colonnes_a_supprimer, création_age_usager, jointure

In [ ]:
import importlib
import src.nettoyage

importlib.reload(src.nettoyage)

Nous avons réalisé des analyses préliminaires sur nos données (disponible dans le fichier pre-processing), cela nous a permis de relever certains problèmes dans les données que nous avons pris en compte pour le nettoyage de nos données ci-dessous (comme les na, les noms de colonnes, les doublons ...)

In [ ]:
donnees_completes = import_donnees()

donnees_completes["caract"][22] = renomer_cle_jointure(donnees_completes["caract"][22], "Num_Acc", "Accident_Id")

# CARACTERISTIQUE
df_caract = concatenation_annees(donnees_completes, "caract")
# LIEUX
df_lieux = concatenation_annees(donnees_completes, "lieux")
# VEHICULE
df_vehicule = concatenation_annees(donnees_completes, "vehicule")
# USAGER
df_usager = concatenation_annees(donnees_completes, "usager")

/home/onyxia/work/Projet_pythonDS/src/donnees.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(nom_fichier_csv, sep=';', encoding='UTF-8')
/home/onyxia/work/Projet_pythonDS/src/donnees.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(nom_fichier_csv, sep=';', encoding='UTF-8')

In [ ]:
mappings = mapping_renommer_colonnes()

In [ ]:
# recodage des noms des colonnes 
df_caract_recoder = recodage(df_caract, mappings["caract"])
df_lieux_recoder = recodage(df_lieux, mappings["lieux"])
df_vehicule_recoder = recodage(df_vehicule, mappings["vehicule"])
df_usager_recoder = recodage(df_usager, mappings["usager"])

# supprimer les doublons de corrections des données dans le fichier lieux 
df_lieux_recoder = df_lieux_recoder.drop_duplicates(subset="Num_Acc", keep="last")

# age pour les usagers
df_usager_recoder = création_age_usager(df_usager_recoder)

In [ ]:
df_final = jointure(df_caract_recoder, df_lieux_recoder, df_vehicule_recoder, df_usager_recoder)

In [ ]:
colonnes_a_supprimer = colonnes_a_supprimer()
df_final = df_final.drop(columns=colonnes_a_supprimer, errors="ignore")

In [ ]:
df_final.columns

Index(['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'agg', 'int',
       'atm', 'col', 'lat', 'long', 'catr', 'circ', 'nbv', 'vosp', 'prof',
       'pr', 'pr1', 'plan', 'lartpc', 'larrout', 'surf', 'infra', 'situ',
       'vma', 'id_vehicule', 'catv', 'obs', 'obsm', 'choc', 'manv',
       'id_usager', 'catu', 'grav', 'sexe', 'trajet', 'secu1', 'secu2',
       'secu3', 'age'],
      dtype='object')

In [ ]:
df_final

KeyboardInterrupt:

In [ ]:
df_final["id_usager"].nunique()
# le nombre de usager devrait etre le meme nombre que le nb de lignes dans df_final ?

377638

In [ ]:
df_final[df_final.duplicated(["Num_Acc", "id_vehicule", "id_usager"], keep=False)]
# pas de doublons !

Empty DataFrame
Columns: [Num_Acc, jour, mois, an, hrmn, lum, dep, com, agg, int, atm, col, adr, lat, long, catr, voie, v1, v2, circ, nbv, vosp, prof, pr, pr1, plan, lartpc, larrout, surf, infra, situ, vma, id_vehicule, catv, obs, obsm, choc, manv, id_usager, catu, grav, sexe, trajet, secu1, secu2, secu3, age]
Index: []

[0 rows x 47 columns]

In [ ]:
df_final[df_final.duplicated("id_usager", keep=False)]

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,...,manv,id_usager,catu,grav,sexe,trajet,secu1,secu2,secu3,age
10,202400000004,24,mars,2024,17:50,Plein jour,14,14118,En agglomération,Intersection en T,...,Tournant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1111,202400000466,30,avril,2024,19:20,Plein jour,79,79191,En agglomération,Intersection à plus de 4 branches,...,Sans changement de direction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
6665,202400002915,20,décembre,2024,16:00,Plein jour,62,62758,En agglomération,Intersection en T,...,Arrêté (hors stationnement),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
11558,202400005069,5,juin,2024,11:44,Plein jour,2B,2B033,En agglomération,Hors intersection,...,Arrêté (hors stationnement),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
15975,202400007018,3,juin,2024,14:50,Plein jour,49,49007,En agglomération,Hors intersection,...,Inconnue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227810,202300044719,1,octobre,2023,16:35,Plein jour,60,60057,En agglomération,Hors intersection,...,A contresens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
229837,202300045599,11,mai,2023,10:02,Plein jour,75,75117,En agglomération,Intersection en X,...,Sans changement de direction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
240635,202300050308,9,mai,2023,20:40,Plein jour,14,14333,En agglomération,Hors intersection,...,Sans changement de direction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
242169,202300050996,4,octobre,2023,06:27,Nuit sans éclairage public,68,68286,Hors agglomération,Intersection en T,...,Tournant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
250618,202300054638,23,août,2023,23:50,Nuit avec éclairage public allumé,14,14715,En agglomération,Hors intersection,...,Autres manœuvres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [ ]:
df_final[df_final["Num_Acc"]==202400000004]

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,...,manv,id_usager,catu,grav,sexe,trajet,secu1,secu2,secu3,age
9,202400000004,24,mars,2024,17:50,Plein jour,14,14118,En agglomération,Intersection en T,...,Inconnue,203 988 573,Conducteur,Blessé léger,Homme,Promenade - loisirs,Casque,Gants (2RM/3RM),Non renseigné,63
10,202400000004,24,mars,2024,17:50,Plein jour,14,14118,En agglomération,Intersection en T,...,Tournant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [ ]:
df_usager[df_usager["Num_Acc"]==202400000004]

,Num_Acc,id_usager,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
9,202400000004,203 988 573,155 781 754,B01,1,1,4,1,1963.0,5,2,6,-1,0,0,-1

In [ ]:
df_vehicule[df_vehicule["Num_Acc"]==202400000004]

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
4,202400000004,155 781 754,B01,3,34,0,2,0,0,1,NaN
5,202400000004,155 781 755,A01,3,7,0,2,3,15,0,NaN

PB : les usagers de certains vehicule ne sont pas repertorié dans les données, comme nous nous interressons aux usgaers car nous regardons notamment les blessures des usagers ne pas avoir d'informations sur eux = pas possible de faire les analyses. Ces usagers représente 64 sur 377638 usagers, nous pouvons donc les supprimés sans nuire à nos analyses, car ils sont peu nombreux.

In [ ]:
df_lieux_recoder["Num_Acc"].nunique()

164526

In [ ]:
df_vehicule_recoder[["Num_Acc", "id_vehicule"]].nunique()

Num_Acc        164526
id_vehicule    280756
dtype: int64

In [ ]:
df_vehicule_recoder[df_vehicule_recoder.duplicated(["Num_Acc", "id_vehicule"], keep=False)] # pas de doublon

Empty DataFrame
Columns: [Num_Acc, id_vehicule, num_veh, senc, catv, obs, obsm, choc, manv, motor, occutc]
Index: []

In [ ]:
df_usager_recoder[["Num_Acc", "id_vehicule", "id_usager"]].nunique() # moins de vehicule que dans vehoicule bien le fair des usager pas repertorié

Num_Acc        164526
id_vehicule    280692
id_usager      377638
dtype: int64

In [ ]:
print(df_final["Num_Acc"].isna().sum())
print(df_final["id_vehicule"].isna().sum())
print(df_final["id_usager"].isna().sum())   # nan pour les usager seulement à supprimer !!!  nombre d'usager = 377638 = nb de ligne dans df_final (a voir d'autre colonne suppression de na ou pas ?)

0
0
64

In [ ]:
df_final = df_final.dropna(subset=["id_usager"])

In [ ]:
import pandas as pd
na_table = pd.DataFrame({
    "nb_na": df_final.isna().sum(),
    "pct_na": (df_final.isna().sum() / len(df_final)) * 100
})

print(na_table)

In [ ]:
sexe_na = df_final[df_final["sexe"].isna()]        # Seulemetn indemne 
age_na = df_final[df_final["age"].isna()]          # tout sauf Tué
secu1_na = df_final[df_final["secu1"].isna()]      # tout 40 Tué sur 10735 ???

circ_na = df_final[df_final["circ"].isna()]        # tout 400 Tué 
infra_na = df_final[df_final["infra"].isna()]      # tout 55 Tué
manv_na = df_final[df_final["manv"].isna()]        # tout 6 Tué
trajet_na = df_final[df_final["trajet"].isna()]    # tout 2000 Tué

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164526 entries, 0 to 164525
Data columns (total 15 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Num_Acc  164526 non-null  int64
 1   jour     164526 non-null  int64
 2   mois     164526 non-null  object
 3   an       164526 non-null  int64
 4   hrmn     164526 non-null  object
 5   lum      164522 non-null  object
 6   dep      164526 non-null  object
 7   com      164526 non-null  object
 8   agg      164526 non-null  object
 9   int      164513 non-null  object
 10  atm      164526 non-null  object
 11  col      164526 non-null  object
 12  adr      159594 non-null  object
 13  lat      164526 non-null  object
 14  long     164526 non-null  object
dtypes: int64(3), object(12)
memory usage: 18.8+ MB

In [ ]:
trajet_na["grav"].unique()

In [ ]:
circ_na.groupby("grav").size()

In [ ]:
df_final.groupby("grav").size()

supprimer les na de ces variables : lum, int, atm, col, prof, plan, surf, situ, catv, 
									obs, obsm, choc, sexe (2%), age (2%), secu1 (2%)
supprimer ces variables : vops, pr, pr1, lartpc, larrout, secu2 (44%), secu3 (96%)

pas mal de na que faire ? : circ (6%), infra (1%), manv (0.03%), trajet (29%) pas supp mais pas utiliser pour le modele ? ou supp apres ?

infra et manv on peut supp pas forcement utile ? circ et trajet garde mais pas supp na 
Peut etre pour ceux qui en ont moyen pas supp garder mais pas pour le modèle comme pour le trajet

In [ ]:
# suppression des NA 
df_final = df_final.dropna(subset=["lum", "int", "atm", "col", "prof", "plan", "surf", "situ", "catv", "obs", "obsm", "choc", "sexe", "age", "secu1"])

In [ ]:
# valeur aberrante nbv, age, vma
df_final["nbv"].unique()
df_final["age"].unique()
df_final["vma"].unique()

def detect_outliers_iqr(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    borne_inf = Q1 - 1.5 * IQR
    borne_sup = Q3 + 1.5 * IQR
    
    return df[(df[col] < borne_inf) | (df[col] > borne_sup)]

In [ ]:
outliers_age = detect_outliers_iqr(df_final, "age")
outliers_age

In [ ]:
outliers_age = detect_outliers_iqr(df_final, "vma")
outliers_age

In [ ]:
outliers_age = detect_outliers_iqr(df_final, "nbv")
outliers_age

In [ ]:
# verif les types 
df_final.dtypes
# ou .info()